#!/bin/sh

# prefix="${XDG_DATA_HOME}/npm" # Prefix is unnecessary (and unsupported) if Node.js is installed by nvm
cache="${XDG_CACHE_HOME}/npm"
init-modules="${XDG_CONFIG_HOME}/npm/config/npm-init.js"
logs-dir="${XDG_STATE_HOME}/npm/logs"